config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "pages#index"

  resources :video_contents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video_content.rb
require "open-uri"

class VideoContent < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @last_videos = VideoContent.all.map do |video|
      video_id = extract_youtube_id(video.url)
      {
        id: video_id,
        title: video.title,
        content: video.content,
        video_id: video.id
      }
    end
  end

  private

  def extract_youtube_id(url)
    regex = /(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/
    match = url.match(regex)
    match[1] if match
  end
end

app/controllers/video_contents_controller.rb
class VideoContentsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_video_content, only: [:show]

  def index
    @videos = VideoContent.all.map do |video|
      video_id = extract_youtube_id(video.url)
      {
        id: video_id,
        title: video.title,
        content: video.content
      }
    end
  end

  def show
    video_id = extract_youtube_id(@video_content.url)
    @video_content = {
      id: @video_content.id,
      video_id: video_id,
      title: @video_content.title,
      content: @video_content.content
    }
  end

  def new
    @video_content = VideoContent.new
  end

  def create
    @video_content = VideoContent.new(video_content_params)
    @video_content.user_id = current_user.id

    if @video_content.save && params[:video_content][:transcription_file].present?
      transcription_file = params[:video_content][:transcription_file]
      transcription_content = transcription_file.read
      
      OpenaiJob.perform_now(@video_content.id, transcription_content)

      redirect_to @video_content, notice: 'Video content was successfully created.'
    else
      render :new
    end
  end

  def update
  end

  private

  def extract_youtube_id(url)
    regex = /(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/
    match = url.match(regex)
    match[1] if match
  end

  def set_video_content
    @video_content = VideoContent.find(params[:id])
  end

  def video_content_params
    params.require(:video_content).permit(:title, :cover, :content, :url, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/video_contents_helper.rb
module VideoContentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubeSummaryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <div class="home-videos-container">
    <% @last_videos.each do |video| %>
      <div class="video-container">
        <iframe width="100%" height="315" src="https://www.youtube.com/embed/<%= video[:id] %>" frameborder="0" allowfullscreen></iframe>
        <h1><%= video[:title] %></h1>
        <p><%= truncate(video[:content], length: 100) %></p>
        <div>
          <%= link_to "SEE MORE", video_content_path(video[:video_id]) %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "Adicionar vídeo", new_video_content_path %>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar">
    <div class="logo">
      <p>YOUTUBE SUMMARY GENERATOR</p>
    </div>
    <div>
      <% if current_user.present? %>
        <p><%= current_user.email %></p>
      <% else %>
        <%= link_to "LOGIN", new_user_session_path, class: "btn-login" %>
      <% end %>
    </div>
  </div>
</div>

app/views/video_contents/_form.html.erb
<%= simple_form_for @video_content do |f| %>
  <%= f.input :title %>
  <%= f.input :url %>
  <%= f.input :transcription_file, as: :file %>
  <%= f.submit class: "btn-submit" %>
<% end %>

app/views/video_contents/index.html.erb
<div class="container">
  <div class="home-videos-container">
    <% @videos.each do |video| %>
      <div class="video-container">
        <iframe width="100%" height="315" src="https://www.youtube.com/embed/<%= video[:id] %>" frameborder="0" allowfullscreen></iframe>
        <h1><%= video[:title] %></h1>
        <p><%= truncate(video[:content], length: 100) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/video_contents/new.html.erb
<div class="container my-4">
  <h1>Generate new video summary</h1>
  <%= render "form", video_content: @video_content %>
</div>

app/views/video_contents/show.html.erb
<div class="container">
  <h2><%= @video_content[:title] %></h2>
  <iframe width="100%" height="615" src="https://www.youtube.com/embed/<%= @video_content[:video_id] %>" frameborder="0" allowfullscreen></iframe>

  <p><%= @video_content[:content] %></p>
</div>